### ISSUE TITLE
Open address book-> If there is no address book with that name it will create a new one. 

### ISSUE THREAD

**Issue by malaura** [sydselynch/index#1]
https://github.com/sydselynch/index/blob/52de51e9d6ee1b34794573d161ff4e11f0c97752/addressbook%20initial%20version/main.py#L43

Recreation:
Press 3
Enter an addressbook name that doesn't exist
What happens: a new address book is created
Wanted: ideally it would say that the address book doesn't exist, and ask the user if they would want to create a new one

**Comment by jinjiel1994** [comment]
Thanks! Fixed.
